### ISSUE TITLE
DLC?

### ISSUE THREAD

**Issue by ghost** [thane98/ignis#11]
I have Conquest and Revelation installed through DLC. How do I include these in the romfs? I can't find any guides on it.

**Comment by thane98** [comment]
The randomizer's designed around the special edition. I would highly recommend using the special edition for Fates hacking in general.

To randomize properly with DLC, you need to dump and unpack the DLC romfs, merge them into the base game, randomize, copy changes back to the DLC, repack, and install.

On paper, you could make this easier by loading DLC paths from a separate directory so that you don't have to copy in / out of the base game's romfs. But this isn't supported currently.

**Comment by ghost** [comment]
Running on Special Edition (from hShop) does work!
